// Modelagem de dados para um sistema de terapia psicologica online

//Usuário
Table usuario {
    id varchar(255) [pk, increment] //GUID
    nome_completo varchar(255) // not null
    email varchar(255) // not null
    cpf varchar(11) // not null 
    telefone varchar(15) // not null 
    data_nascimento date // not null
    genero varchar(1) // not null 
    senha varchar(255) // not null
    role varchar // not null
    email_verificado boolean // not null
    usuario_aprovado boolean // not null
    endereco_completo varchar(255) // not null
    created_at timestamp

}

//Psicólogo
Table psicologo {
    usuario_id varchar [pk, ref: > usuario.id] // Um psicólogo é um usuário
    crp varchar(255) // not null
    descricao varchar(255) // not null 
    carteira_crp blob // not null  
}

Table paciente {
    usuario_id varchar [pk, ref: > usuario.id] // Um paciente é um usuário
    foto_rg_frente blob // not null
    foto_rg_verso blob // not null
    comprovante_residencia blob // not null
    relatorio_medico blob // not null
    pdf_formatado blob // not null
    crm_medico integer // not null
nome_medico varchar(255) // not null
cid varchar(255) // not null
uf_crm varchar(2) // not null

}

//Agenda
Table agenda {
    psicologo_id varchar [pk, ref: > psicologo.usuario_id]
    data_agenda datetime [pk]
}

//Agendamento
Table agendamento {
    id integer [pk, increment]
    paciente_id string [pk, ref: > paciente.usuario_id]
    agenda_data datetime [pk, ref: - agenda.data_agenda]
}

Table sessao {
    agendamento_id integer [pk, ref: - agendamento.id]
    data_inicio datetime // not null
    data_fim datetime // not null
}

// Avaliação do psicologo
Table avaliacao {
    sessao_id integer [pk, ref: - sessao.agendamento_id]
    nota integer // not null
    comentario varchar(255) // not null
}

Table mensagem {
    usuario_fonte_id integer [pk, ref: > usuario.id]
    usuario_destino_id integer [pk, ref: > usuario.id]
    texto varchar(255) // not null
    data datetime // not null
}
/*
public class Paciente : BaseEntity.BaseEntity
{

    [Key]
    [ForeignKey("User")]
    public string UserId {  get; set; }
    public virtual User User { get; set; }
    
    public byte[] FotoRgFrente { get; set; }
    public byte[] FotoRgVerso {  get; set; }
    public byte[] ComprovanteResidencia { get; set; }
    public byte[] RelatorioMedico { get; set; }
    public byte[] PDFFormatado { get; set; }
    public int CrmMedico { get; set; }
    public string NomeMedico { get; set; }
    public string Cid { get; set; }
    public string UfCrm {  get; set; }

}

*/